from app.models.cliente import Cliente
from app.models.mesa import Mesa
from app.models.empleado import Empleado
from app.models.categoria import Categoria
from app.models.ingrediente import Ingrediente
from app.models.plato import Plato
from app.models.plato_ingrediente import PlatoIngrediente
from app.models.pedido import Pedido
from app.models.detalle_pedido import DetallePedido